### PR TITLE
Add 'initClipFactor', 'fit' and 'thumbOverflow' parameters in widget constructor

### PR DESCRIPTION
**Pull request by sdabet-orpheo**

### CODE REVIEW

**Comment by apgapg** [comment]
Hi @sdabet-orpheo Can you please provide a sample example code and screenshot for better visibility?
Thank you for adding this cool feature.

**Comment by sdabet-orpheo** [comment]
Here is an example with:

- **initClipFactor: 0** => the "after" image is fully expanded initially
- **fit: StackFit.expand** => the widget expands
- **thumbOverflow: true** => the thumb can overflow the widget, so that the expanded image can take whole available space

```
    Column(
        children: [
          Expanded(child: BeforeAfter(
            beforeImage: Image.network(beforeImage.uri, fit: boxFit),
            afterImage: Image.network(afterImage.uri, fit: boxFit),
            isVertical: false,
            initClipFactor: 0,
            fit: StackFit.expand,
            thumbOverflow: true,
          )),
        ]
    );
```

https://user-images.githubusercontent.com/79854215/140721779-d1782010-c583-4c37-8894-6066c5ecbf21.mov

**Comment by sdabet-orpheo** [comment]
@apgapg I'm not sure why the build failed, can you please check it ?

**Comment by apgapg** [comment]
@sdabet-orpheo Looks like its something related to flutter version. 
@xsahil03x Its a high need we migrate to github actions

**Comment by sdabet-orpheo** [comment]
I merged the latest master commits into the PR.

**Comment by sdabet-orpheo** [comment]
Hi, could you please check this pull request ?

**Comment by xsahil03x** [comment]
Closing in favor of [v3.0.0](https://pub.dev/packages/before_after/versions/3.0.0)

**Comment by sdabet-orpheo** [comment]
@xsahil03x would it be possible to add the `fit` param in 3.0.0 ?

**Pull request closed without merging**
